services:
  beast-travel:
    build:
      context: .
      dockerfile: Dockerfile
    image: beast-travel:bt-023
    container_name: beast-travel
    working_dir: /app

    command: >
      bash -c "
      rm -rf .next &&
      npm install &&
      npm run dev -- --hostname 0.0.0.0
      "

    ports:
      - "3005:3000"

    volumes:
      - .:/app

    tty: true
    stdin_open: true
